### ISSUE TITLE
Unable to add text: error in AddTextFunction

### ISSUE THREAD

**Issue by krutoivoker** [poetaster/harbour-clipper#5]
Steps:

1. Open video file
2. Click on Text then type test string into corresponding field
3. Confirm text adding by pressing on Checkmark button

Actual result: Error in AddTextFunction 
Expected result: Text added
![Снимок_Экрана_20231126_001](https://github.com/poetaster/harbour-clipper/assets/6212732/0fcc5859-1be5-47fc-a60f-ebf7fa4f398a)

**Comment by poetaster** [comment]
Thanks for reporting! The most recent Jolla ffmpeg versions don't appear to have:
> --enable-libfreetype and --enable-libharfbuzz

which means the 'drawtext' filter is not available. I'm looking at an alternative (that doesn't require me to maintain ffmpeg')

**Comment by poetaster** [comment]
I've made a request upstream to see if it can be fixed here. https://github.com/sailfishos/ffmpeg/pull/9

**Comment by poetaster** [comment]
The test versions compiled here: https://repo.sailfishos.org/obs/home:/poetaster/4.5.0.18_aarch64/aarch64/ fix this issue. There is another issue with subtitles I'm working on. But this one works. It should make it to the next SFOS release.
If you download those, install them:
```
pkcon install-local ffmpeg-5.1.3\+drawtext.20231128093602.66e582a-1.3.1.jolla.aarch64.rpm ffmpeg-tools-5.1.3+drawtext.20231128093602.66e582a-1.3.1.jolla.aarch64.rpm
```

**Comment by krutoivoker** [comment]
I can confirm that error is gone with fixed ffmpegs.
